server {
    listen 8080;
    server_name kustika.mx www.kustika.mx;

    return 301 https://kustika.com.mx$request_uri;
}

server {
    listen 8080 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
