import heroImage from "../../../shared/assets/images/hero/hero.jpg";
import type { Event } from "./event";

export const mockEvents: Event[] = [
    {
        id: "evt-neon-eclipse-2026",
        slug: "neon-eclipse",
        title: "Neon Eclipse",
        subtitle: "Una noche de electronica, visuales inmersivos y energia al limite.",
        description:
            "Neon Eclipse reune DJs nacionales, barras invitadas y una produccion visual de alto impacto para vivir una noche completa en la ciudad.",
        location: "Queretaro",
        venueName: "Distrito Vivo",
        address: "Av. Constituyentes 102, Centro",
        city: "Queretaro",
        date: "24 Oct 2026",
        time: "20:00",
        price: 890,
        image: heroImage,
        category: "Musica",
        status: "available",
        organizer: "Evenxa Nights",
        capacity: 1200,
        tags: ["Electronica", "Visuales", "After"],
        highlights: [
            "Escenario principal con visuales inmersivos",
            "Acceso digital desde tu cuenta Evenxa",
            "Zona de alimentos y barras dentro del venue",
        ],
        schedule: [
            {
                time: "20:00",
                label: "Apertura de puertas",
                description: "Ingreso general, activacion de barras y zona de foto.",
            },
            {
                time: "21:30",
                label: "Warm up",
                description: "Set de apertura con talento local.",
            },
            {
                time: "23:00",
                label: "Show principal",
                description: "Presentacion central con produccion audiovisual completa.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 890,
                description: "Acceso al evento y zonas generales.",
                available: true,
            },
            {
                id: "vip",
                name: "VIP",
                price: 1490,
                description: "Acceso preferente y zona elevada.",
                available: true,
            },
        ],
        policies: [
            "Evento para mayores de 18 anos.",
            "El boleto digital se valida una sola vez en acceso.",
            "No se permite el ingreso con alimentos o bebidas externas.",
        ],
    },
    {
        id: "evt-midnight-city-tour-2026",
        slug: "midnight-city-tour",
        title: "Midnight City Tour",
        subtitle: "Recorre la ciudad de noche con musica, paradas sorpresa y crew invitado.",
        description:
            "Midnight City Tour combina transporte, experiencias urbanas y una ruta curada por hotspots de la CDMX para descubrir la ciudad de otra forma.",
        location: "CDMX",
        venueName: "Punto Reforma",
        address: "Paseo de la Reforma 222, Juarez",
        city: "Ciudad de Mexico",
        date: "12 Nov 2026",
        time: "19:30",
        price: 1200,
        image: heroImage,
        category: "Experiencias",
        status: "available",
        organizer: "Evenxa Experiences",
        capacity: 180,
        tags: ["Tour", "Urbano", "Noche"],
        highlights: [
            "Ruta nocturna con staff y transporte incluido",
            "Tres paradas seleccionadas por el equipo Evenxa",
            "Pulsera digital y check-in express",
        ],
        schedule: [
            {
                time: "19:30",
                label: "Check-in",
                description: "Validacion de boletos y entrega de pulseras.",
            },
            {
                time: "20:15",
                label: "Salida",
                description: "Inicio de ruta desde Punto Reforma.",
            },
            {
                time: "00:30",
                label: "Cierre",
                description: "Regreso al punto inicial.",
            },
        ],
        ticketTiers: [
            {
                id: "tour",
                name: "Tour completo",
                price: 1200,
                description: "Incluye acceso a la ruta y transporte.",
                available: true,
            },
            {
                id: "tour-plus",
                name: "Tour Plus",
                price: 1680,
                description: "Incluye ruta, transporte y acceso preferente.",
                available: true,
            },
        ],
        policies: [
            "Presentate 30 minutos antes de la salida.",
            "El itinerario puede ajustarse por clima o transito.",
            "La compra no incluye consumos personales.",
        ],
    },
    {
        id: "evt-solar-sessions-2026",
        slug: "solar-sessions",
        title: "Solar Sessions",
        subtitle: "Tarde de musica independiente, gastronomia y mercado creativo.",
        description:
            "Solar Sessions es un encuentro al aire libre con bandas emergentes, marcas locales y espacios para convivir antes del atardecer.",
        location: "Guadalajara",
        venueName: "Foro Atemporal",
        address: "C. Argentina 75, Americana",
        city: "Guadalajara",
        date: "28 Nov 2026",
        time: "16:00",
        price: 650,
        image: heroImage,
        category: "Festival",
        status: "soon",
        organizer: "Evenxa Live",
        capacity: 850,
        tags: ["Indie", "Food", "Market"],
        highlights: [
            "Lineup curado con proyectos emergentes",
            "Mercado local y area gastronomica",
            "Ambiente al aire libre con acceso familiar",
        ],
        schedule: [
            {
                time: "16:00",
                label: "Apertura",
                description: "Ingreso, mercado creativo y food court.",
            },
            {
                time: "18:00",
                label: "Primer bloque",
                description: "Presentaciones de bandas invitadas.",
            },
            {
                time: "21:00",
                label: "Headliner",
                description: "Show de cierre en escenario principal.",
            },
        ],
        ticketTiers: [
            {
                id: "early",
                name: "Early access",
                price: 650,
                description: "Precio de lanzamiento por tiempo limitado.",
                available: false,
            },
            {
                id: "general",
                name: "General",
                price: 790,
                description: "Acceso general al festival.",
                available: true,
            },
        ],
        policies: [
            "Menores de edad ingresan acompanados por un adulto.",
            "No se permite reingreso despues de validar el boleto.",
            "Evento sujeto a lineamientos del venue.",
        ],
    },
    {
        id: "evt-mestiza-live-2026",
        slug: "mestiza-live",
        title: "Mestiza Live",
        subtitle: "Ritmos latinos, baile y una produccion pensada para celebrar.",
        description:
            "Mestiza Live junta musica latina, invitados especiales y una pista amplia para una experiencia vibrante de principio a fin.",
        location: "Monterrey",
        venueName: "Arena Barrio",
        address: "Calz. Madero 410, Centro",
        city: "Monterrey",
        date: "05 Dic 2026",
        time: "21:00",
        price: 980,
        image: heroImage,
        category: "Concierto",
        status: "available",
        organizer: "Evenxa Music",
        capacity: 2200,
        tags: ["Latino", "Baile", "Live"],
        highlights: [
            "Show en vivo con invitados especiales",
            "Pista central y zonas preferentes",
            "Compra y validacion digital en Evenxa",
        ],
        schedule: [
            {
                time: "21:00",
                label: "Puertas",
                description: "Apertura del venue y acceso a zonas.",
            },
            {
                time: "22:00",
                label: "DJ set",
                description: "Musica previa al show principal.",
            },
            {
                time: "23:15",
                label: "Mestiza Live",
                description: "Presentacion principal.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 980,
                description: "Acceso a pista general.",
                available: true,
            },
            {
                id: "preferente",
                name: "Preferente",
                price: 1750,
                description: "Zona preferente cercana al escenario.",
                available: true,
            },
        ],
        policies: [
            "Acceso permitido solo con boleto vigente.",
            "No se hacen cambios de zona el dia del evento.",
            "El venue puede negar acceso por incumplir reglas internas.",
        ],
    },
    {
        id: "evt-risas-al-centro-2026",
        slug: "risas-al-centro",
        title: "Risas al Centro",
        subtitle: "Stand up, invitados sorpresa y una noche de comedia sin filtro.",
        description:
            "Risas al Centro reune comediantes emergentes y nombres invitados en un formato cercano, rapido y perfecto para cerrar la semana.",
        location: "CDMX",
        venueName: "Foro Roma",
        address: "C. Durango 88, Roma Norte",
        city: "Ciudad de Mexico",
        date: "18 Dic 2026",
        time: "20:30",
        price: 420,
        image: heroImage,
        category: "Comedia",
        status: "available",
        organizer: "Evenxa Comedy",
        capacity: 320,
        tags: ["Comedia", "Standup", "Show"],
        highlights: [
            "Lineup con talento emergente e invitados especiales",
            "Mesa compartida y servicio dentro del foro",
            "Acceso digital con check-in express",
        ],
        schedule: [
            {
                time: "20:30",
                label: "Ingreso",
                description: "Apertura de puertas y asignacion de zonas.",
            },
            {
                time: "21:00",
                label: "Open mic",
                description: "Bloque de apertura con talento local.",
            },
            {
                time: "22:00",
                label: "Show principal",
                description: "Presentaciones centrales de la noche.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 420,
                description: "Acceso general al foro.",
                available: true,
            },
            {
                id: "mesa",
                name: "Mesa preferente",
                price: 690,
                description: "Zona preferente con mejor vista al escenario.",
                available: true,
            },
        ],
        policies: [
            "Evento recomendado para mayores de 18 anos.",
            "Se recomienda llegar 20 minutos antes.",
            "No se permite grabar el show completo.",
        ],
    },
    {
        id: "evt-norte-vivo-2026",
        slug: "norte-vivo",
        title: "Norte Vivo",
        subtitle: "Regional, banda invitada y una noche para cantar fuerte.",
        description:
            "Norte Vivo celebra sonidos regionales con artistas invitados, pista amplia y una produccion pensada para bailar y cantar de principio a fin.",
        location: "Monterrey",
        venueName: "Patio Acero",
        address: "Av. Fundidora 501, Obrera",
        city: "Monterrey",
        date: "09 Ene 2027",
        time: "21:30",
        price: 760,
        image: heroImage,
        category: "Regional",
        status: "available",
        organizer: "Evenxa Regional",
        capacity: 1500,
        tags: ["Regional", "Mexico", "Baile"],
        highlights: [
            "Escenario principal con artistas regionales",
            "Zona de baile y barras dentro del venue",
            "Accesos digitales para entrada rapida",
        ],
        schedule: [
            {
                time: "21:30",
                label: "Puertas",
                description: "Ingreso y apertura de zona de barras.",
            },
            {
                time: "22:30",
                label: "Invitados",
                description: "Bloque con talento regional invitado.",
            },
            {
                time: "00:00",
                label: "Show estelar",
                description: "Presentacion principal de Norte Vivo.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 760,
                description: "Acceso general a pista.",
                available: true,
            },
            {
                id: "palco",
                name: "Palco",
                price: 1320,
                description: "Vista elevada y acceso preferente.",
                available: true,
            },
        ],
        policies: [
            "Evento para mayores de 18 anos.",
            "No se permiten objetos punzocortantes.",
            "El acceso puede negarse por incumplir reglas del venue.",
        ],
    },
    {
        id: "evt-sabor-latino-2027",
        slug: "sabor-latino",
        title: "Sabor Latino",
        subtitle: "Salsa, urbano latino y una pista encendida toda la noche.",
        description:
            "Sabor Latino mezcla musica en vivo, DJ sets y dinamicas de baile para una experiencia latina con energia continua.",
        location: "Guadalajara",
        venueName: "Terraza Chapultepec",
        address: "Av. Chapultepec Sur 180, Americana",
        city: "Guadalajara",
        date: "16 Ene 2027",
        time: "20:00",
        price: 540,
        image: heroImage,
        category: "Musica latina",
        status: "available",
        organizer: "Evenxa Latin",
        capacity: 700,
        tags: ["Latino", "Baile", "Musica"],
        highlights: [
            "DJ set latino y banda invitada",
            "Pista abierta para baile social",
            "Zona gastronomica con sabores latinos",
        ],
        schedule: [
            {
                time: "20:00",
                label: "Apertura",
                description: "Ingreso y activacion de food court.",
            },
            {
                time: "21:00",
                label: "Clase abierta",
                description: "Bloque corto de baile para iniciar la noche.",
            },
            {
                time: "22:00",
                label: "Live set",
                description: "Musica en vivo y DJ set latino.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 540,
                description: "Acceso general a terraza y pista.",
                available: true,
            },
            {
                id: "plus",
                name: "Latino Plus",
                price: 890,
                description: "Acceso preferente y bebida de bienvenida.",
                available: true,
            },
        ],
        policies: [
            "Menores de edad ingresan acompanados por un adulto.",
            "No se permite reingreso despues del check-in.",
            "La programacion puede cambiar sin previo aviso.",
        ],
    },
    {
        id: "evt-bazar-sonoro-2027",
        slug: "bazar-sonoro",
        title: "Bazar Sonoro",
        subtitle: "Festival de proyectos locales, comida y mercado creativo.",
        description:
            "Bazar Sonoro une musica independiente, marcas locales, food trucks y espacios para convivir al aire libre durante todo el dia.",
        location: "Queretaro",
        venueName: "Parque Alameda",
        address: "Centro Historico, Alameda Hidalgo",
        city: "Queretaro",
        date: "24 Ene 2027",
        time: "13:00",
        price: 390,
        image: heroImage,
        category: "Festival",
        status: "soon",
        organizer: "Evenxa Market",
        capacity: 2000,
        tags: ["Festival", "Food", "Market"],
        highlights: [
            "Mercado creativo con marcas locales",
            "Escenario alternativo con bandas emergentes",
            "Zona familiar y area gastronomica",
        ],
        schedule: [
            {
                time: "13:00",
                label: "Apertura",
                description: "Ingreso, bazar y zona gastronomica.",
            },
            {
                time: "16:00",
                label: "Bandas locales",
                description: "Primer bloque de presentaciones.",
            },
            {
                time: "19:30",
                label: "Cierre musical",
                description: "Show de cierre en escenario principal.",
            },
        ],
        ticketTiers: [
            {
                id: "early",
                name: "Early",
                price: 390,
                description: "Acceso por precio de lanzamiento.",
                available: true,
            },
            {
                id: "general",
                name: "General",
                price: 520,
                description: "Acceso general al festival.",
                available: true,
            },
        ],
        policies: [
            "Evento pet friendly en zonas senaladas.",
            "No se permite ingresar con bebidas externas.",
            "El acceso esta sujeto al aforo permitido.",
        ],
    },
    {
        id: "evt-ruta-secreta-2027",
        slug: "ruta-secreta",
        title: "Ruta Secreta",
        subtitle: "Una experiencia urbana con paradas sorpresa y crew invitado.",
        description:
            "Ruta Secreta lleva a los asistentes por espacios ocultos de la ciudad con musica, dinamicas y momentos sorpresa durante el recorrido.",
        location: "CDMX",
        venueName: "Punto Condesa",
        address: "Av. Tamaulipas 120, Condesa",
        city: "Ciudad de Mexico",
        date: "31 Ene 2027",
        time: "18:30",
        price: 1100,
        image: heroImage,
        category: "Experiencias",
        status: "available",
        organizer: "Evenxa Experiences",
        capacity: 120,
        tags: ["Experiencias", "Tour", "Urbano"],
        highlights: [
            "Recorrido guiado con staff Evenxa",
            "Tres paradas sorpresa con activaciones",
            "Transporte incluido durante la ruta",
        ],
        schedule: [
            {
                time: "18:30",
                label: "Check-in",
                description: "Validacion de boletos y briefing inicial.",
            },
            {
                time: "19:00",
                label: "Inicio de ruta",
                description: "Salida desde Punto Condesa.",
            },
            {
                time: "23:30",
                label: "Cierre",
                description: "Regreso al punto de encuentro.",
            },
        ],
        ticketTiers: [
            {
                id: "ruta",
                name: "Ruta completa",
                price: 1100,
                description: "Incluye transporte y acceso a activaciones.",
                available: true,
            },
            {
                id: "ruta-plus",
                name: "Ruta Plus",
                price: 1580,
                description: "Incluye ruta completa y acceso preferente.",
                available: true,
            },
        ],
        policies: [
            "Presentate 30 minutos antes del inicio.",
            "La ruta puede ajustarse por clima o movilidad.",
            "La compra no incluye consumos personales.",
        ],
    },
];
