// app/router/routes.ts

export const routes = {
    home: "/",
    app: "/app",
    events: "/eventos",
    raffles: "/rifas",
    categories: "/categorias",
    myTickets: "/mis-boletos",
    eventCustomer: "/panel-eventos",
    organizerRequest: "/solicitud-organizador",
    admin: "/admin",
    adminEvents: "/admin/eventos",
    adminRequests: "/admin/solicitudes",
    adminProfile: "/admin/perfil",
    profile: "/perfil",
    editProfile: "/perfil/editar",
    categoryDetailBase: "/categorias",
    categoryDetail: (categoryId: string) => `/categorias/${categoryId}`,
    login: "/login",
    googleCallback: "/auth/google/callback",
    recoverPassword: "/recuperar-password",
    register: "/registro",
    eventDetailBase: "/eventos",
    eventDetail: (eventId: string) => `/eventos/${eventId}`,
    eventCheckout: (eventId: string) => `/eventos/${eventId}/comprar`,
} as const;
